// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Utils$ReasonTree = require("./Utils.bs.js");

Utils$ReasonTree.printDir(0, "node_modules", "../../");

/*  Not a pure module */
